### ISSUE TITLE
Encoding failed

### ISSUE THREAD

**Issue by Alexei007** [pascalbaljet/encrypted-hls-with-laravel-ffmpeg-demo#1]
![image](https://user-images.githubusercontent.com/26039956/111610035-e0ac2180-8815-11eb-99f4-433e6b03d22c.png)

**Comment by jayenne** [comment]
same problem here `using php 7.4.16 and ffmpeg 3.4.8`

it's simply a clean clone run in dicker via laradock. any thougths?

laravel.log:
```
Unrecognized option 'master_pl_name'.
Error splitting the argument list: Option not found
```

I suspected my version of ffmpeg is the problem and so updated it to ffmpeg-4 and all is fine :0)

I used: `apt-get install ffmpeg` but you may need `sudo apt-get install ffmpeg`

HIH.

**Comment by pascalbaljet** [comment]
Your FFmpeg builds are too old:
https://stackoverflow.com/questions/66190725/ffmpeg-returns-error-unrecognized-option-master-pl-name

**Comment by Alexei007** [comment]
> Your FFmpeg builds are too old:
> https://stackoverflow.com/questions/66190725/ffmpeg-returns-error-unrecognized-option-master-pl-name

Thanks for your reply, I found the reason why the program reported an error. Relevant configuration needs to be enabled, Such as 
```
--enable-libx265
 ```

**Comment by Alexei007** [comment]
> Your FFmpeg builds are too old:
> https://stackoverflow.com/questions/66190725/ffmpeg-returns-error-unrecognized-option-master-pl-name

Thanks for your reply )
