### ISSUE TITLE
HLSExporter" not found Error

### ISSUE THREAD

**Issue by froutanramin** [pascalbaljet/encrypted-hls-with-laravel-ffmpeg-demo#3]
Hi , i got this error when i want to use encrypted version. how can i fix this ?

![Screenshot-2024-05-16-at-11 19 11](https://github.com/pascalbaljet/encrypted-hls-with-laravel-ffmpeg-demo/assets/74067731/16d7c446-7d1b-4628-9e08-3b6c05028c15)

**Comment by pascalbaljet** [comment]
Import the full namespace.
